---
title: "Code for Finance workshop"
author: "Zhengkai Fu"
date: "07/07/2020"
output: html_document
---
# Load library
```{r library, message=FALSE}
library(tidyverse)
```

# Simulation for diversification
## Perfect Correlation
```{r create 2 perfectly correlated assets}
asset_1_return <- rnorm(100, mean = 0.03, sd = 0.02)

# perfect linear correlation
asset_2_return <- 0.09 + asset_1_return * 1.8

combined_return <- data.frame(cbind(asset_1_return, asset_2_return))

cor(asset_1_return, asset_2_return)
sqrt(var(asset_2_return))

combined_return %>%
  ggplot(aes(x=asset_1_return, y = asset_2_return)) +
  geom_point

# 2 assets' summary
mean_1 = mean(asset_1_return)
mean_2 = mean(asset_2_return)
sd_1 = sqrt(var(asset_1_return))
sd_2 = sqrt(var(asset_2_return))
avg_perfect <-  data.frame(cbind(c(mean_1, mean_2), c(sd_1, sd_2)))
colnames(avg_perfect) <- c("mean", "stdev")

# TODO: ASSET COMBINATION OF 2 AND ADD INTO PLOT BELOW

avg_perfect %>%
  ggplot(aes(x=stdev, y=mean)) +
  geom_point()


```
